from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum
from hashlib import sha256
import json
from typing import Mapping, Any


class DeploymentGrantStanding(StrEnum):
    NONE="NONE"; ACTIVE="ACTIVE"; REVOKED="REVOKED"; EXPIRED="EXPIRED"; SUSPENDED="SUSPENDED"
    SUPERSEDED_TARGET_REVALIDATION_REQUIRED="SUPERSEDED_TARGET_REVALIDATION_REQUIRED"; INVALID="INVALID"


class GrantEvent(StrEnum):
    GRANT_CREATED="GRANT_CREATED"; GRANT_REVOKED="GRANT_REVOKED"; GRANT_EXPIRED="GRANT_EXPIRED"
    SAFETY_HOLD_PLACED="SAFETY_HOLD_PLACED"; TARGET_SUPERSEDED="TARGET_SUPERSEDED"; REVALIDATED="REVALIDATED"
    SAFETY_HOLD_REMOVED_AND_REVALIDATED="SAFETY_HOLD_REMOVED_AND_REVALIDATED"; REVALIDATION_DENIED="REVALIDATION_DENIED"


class RuntimeDeploymentStanding(StrEnum):
    NONE="NONE"; AUTHORIZED_NOT_ACTIVE="AUTHORIZED_NOT_ACTIVE"; ACTIVATING="ACTIVATING"; ACTIVE="ACTIVE"
    STOPPING="STOPPING"; STOPPED="STOPPED"; ACTIVATION_FAILED="ACTIVATION_FAILED"; SUSPENDED="SUSPENDED"
    SAFETY_HELD="SAFETY_HELD"; REVALIDATION_REQUIRED="REVALIDATION_REQUIRED"; REVOKED="REVOKED"; INVALID="INVALID"


class RuntimeEvent(StrEnum):
    RUNTIME_DEPLOYMENT_CONSTITUTED="RUNTIME_DEPLOYMENT_CONSTITUTED"; ACTIVATION_REQUESTED="ACTIVATION_REQUESTED"
    ACTIVATION_RETRY_REQUESTED="ACTIVATION_RETRY_REQUESTED"; ACTIVATED="ACTIVATED"; ACTIVATION_FAILED="ACTIVATION_FAILED"
    STOP_REQUESTED="STOP_REQUESTED"; STOPPED="STOPPED"; GRANT_REVOKED="GRANT_REVOKED"; GRANT_EXPIRED="GRANT_EXPIRED"
    SAFETY_HOLD_PLACED="SAFETY_HOLD_PLACED"; SAFETY_HOLD_REMOVED="SAFETY_HOLD_REMOVED"; TARGET_SUPERSEDED="TARGET_SUPERSEDED"
    POLICY_SUSPEND="POLICY_SUSPEND"; REVALIDATED="REVALIDATED"; REVALIDATION_DENIED="REVALIDATION_DENIED"


_GRANT={
("NONE","GRANT_CREATED","DEFAULT"):"ACTIVE",
("ACTIVE","GRANT_REVOKED","DEFAULT"):"REVOKED",
("SUSPENDED","GRANT_REVOKED","DEFAULT"):"REVOKED",
("SUPERSEDED_TARGET_REVALIDATION_REQUIRED","GRANT_REVOKED","DEFAULT"):"REVOKED",
("ACTIVE","SAFETY_HOLD_PLACED","DEFAULT"):"SUSPENDED",
("ACTIVE","TARGET_SUPERSEDED","REVALIDATION_REQUIRED"):"SUPERSEDED_TARGET_REVALIDATION_REQUIRED",
("ACTIVE","TARGET_SUPERSEDED","DEACTIVATION_REQUIRED"):"SUPERSEDED_TARGET_REVALIDATION_REQUIRED",
("ACTIVE","TARGET_SUPERSEDED","NO_ACTION_REQUIRED"):"ACTIVE",
("SUPERSEDED_TARGET_REVALIDATION_REQUIRED","REVALIDATED","REVALIDATED_CONTINUE_ALLOWED"):"ACTIVE",
("SUSPENDED","SAFETY_HOLD_REMOVED_AND_REVALIDATED","REVALIDATED_CONTINUE_ALLOWED"):"ACTIVE",
("SUPERSEDED_TARGET_REVALIDATION_REQUIRED","REVALIDATION_DENIED","DEFAULT"):"SUPERSEDED_TARGET_REVALIDATION_REQUIRED",
("SUSPENDED","REVALIDATION_DENIED","DEFAULT"):"SUSPENDED",
}
_RUNTIME={
("NONE","RUNTIME_DEPLOYMENT_CONSTITUTED","DEFAULT"):"AUTHORIZED_NOT_ACTIVE",
("AUTHORIZED_NOT_ACTIVE","ACTIVATION_REQUESTED","ACTIVATION_ADMISSIBLE"):"ACTIVATING",
("ACTIVATION_FAILED","ACTIVATION_RETRY_REQUESTED","ACTIVATION_ADMISSIBLE"):"ACTIVATING",
("ACTIVATING","ACTIVATED","DEFAULT"):"ACTIVE",
("ACTIVATING","ACTIVATION_FAILED","DEFAULT"):"ACTIVATION_FAILED",
("ACTIVATING","STOP_REQUESTED","DEFAULT"):"STOPPING",
("ACTIVE","STOP_REQUESTED","DEFAULT"):"STOPPING",
("REVOKED","STOP_REQUESTED","DEFAULT"):"STOPPING",
("SUSPENDED","STOP_REQUESTED","DEFAULT"):"STOPPING",
("SAFETY_HELD","STOP_REQUESTED","DEFAULT"):"STOPPING",
("REVALIDATION_REQUIRED","STOP_REQUESTED","DEFAULT"):"STOPPING",
("STOPPING","STOPPED","DEFAULT"):"STOPPED",
("ACTIVE","TARGET_SUPERSEDED","REVALIDATION_REQUIRED"):"REVALIDATION_REQUIRED",
("ACTIVE","TARGET_SUPERSEDED","DEACTIVATION_REQUIRED"):"REVALIDATION_REQUIRED",
("ACTIVE","TARGET_SUPERSEDED","NO_ACTION_REQUIRED"):"ACTIVE",
("AUTHORIZED_NOT_ACTIVE","SAFETY_HOLD_PLACED","DEFAULT"):"SAFETY_HELD",
("ACTIVATION_FAILED","SAFETY_HOLD_PLACED","DEFAULT"):"SAFETY_HELD",
("ACTIVE","SAFETY_HOLD_PLACED","DEFAULT"):"SAFETY_HELD",
("ACTIVATING","SAFETY_HOLD_PLACED","DEFAULT"):"SAFETY_HELD",
("SAFETY_HELD","SAFETY_HOLD_REMOVED","DEFAULT"):"REVALIDATION_REQUIRED",
("SUSPENDED","SAFETY_HOLD_REMOVED","DEFAULT"):"REVALIDATION_REQUIRED",
("REVALIDATION_REQUIRED","REVALIDATED","CONTINUE_ACTIVE"):"ACTIVE",
("REVALIDATION_REQUIRED","REVALIDATED","CONTINUE_INACTIVE"):"AUTHORIZED_NOT_ACTIVE",
("SAFETY_HELD","REVALIDATION_DENIED","DEFAULT"):"SAFETY_HELD",
("REVALIDATION_REQUIRED","REVALIDATION_DENIED","DEFAULT"):"REVALIDATION_REQUIRED",
("AUTHORIZED_NOT_ACTIVE","GRANT_REVOKED","DEFAULT"):"REVOKED",
("ACTIVATION_FAILED","GRANT_REVOKED","DEFAULT"):"REVOKED",
("ACTIVE","GRANT_REVOKED","REVOKE_RUNNING"):"REVOKED",
("ACTIVE","GRANT_REVOKED","RUNTIME_MAY_CONTINUE"):"ACTIVE",
("ACTIVATING","GRANT_REVOKED","DEFAULT"):"REVOKED",
("SAFETY_HELD","GRANT_REVOKED","DEFAULT"):"REVOKED",
("REVALIDATION_REQUIRED","GRANT_REVOKED","DEFAULT"):"REVOKED",
("ACTIVE","POLICY_SUSPEND","DEFAULT"):"SUSPENDED",
("SUSPENDED","REVALIDATED","CONTINUE_ACTIVE"):"ACTIVE",
("SUSPENDED","REVALIDATED","CONTINUE_INACTIVE"):"AUTHORIZED_NOT_ACTIVE",
}


def grant_next(state: DeploymentGrantStanding,event: GrantEvent,condition: str="DEFAULT")->DeploymentGrantStanding:
    try:return DeploymentGrantStanding(_GRANT[(state.value,event.value,condition)])
    except KeyError as exc: raise PermissionError(f"INVALID_GRANT_TRANSITION:{state.value}+{event.value}+{condition}") from exc


def runtime_next(state: RuntimeDeploymentStanding,event: RuntimeEvent,condition: str="DEFAULT")->RuntimeDeploymentStanding:
    try:return RuntimeDeploymentStanding(_RUNTIME[(state.value,event.value,condition)])
    except KeyError as exc: raise PermissionError(f"INVALID_RUNTIME_TRANSITION:{state.value}+{event.value}+{condition}") from exc


@dataclass(frozen=True, slots=True)
class RuntimeRealizationSnapshot:
    snapshot_id:str
    target_ref:str
    runtime_profile:Mapping[str,Any]
    environment:Mapping[str,Any]
    provider_binding:Mapping[str,Any]
    secret_scope:Mapping[str,Any]
    permission_scope:Mapping[str,Any]
    policy:Mapping[str,Any]
    runtime_boundary:Mapping[str,Any]

    @property
    def identity(self)->str:
        raw=json.dumps({
            "target_ref":self.target_ref,"runtime_profile":self.runtime_profile,"environment":self.environment,
            "provider_binding":self.provider_binding,"secret_scope":self.secret_scope,"permission_scope":self.permission_scope,
            "policy":self.policy,"runtime_boundary":self.runtime_boundary,
        },sort_keys=True,separators=(",",":")).encode()
        return sha256(raw).hexdigest()


@dataclass(frozen=True, slots=True)
class DeploymentAuthorityRecord:
    deployment_id:str
    frozen_artifact_id:str
    lineage_id:str
    baseline_id:str
    grant_id:str
    grant_standing:DeploymentGrantStanding
    runtime_standing:RuntimeDeploymentStanding
    realization_snapshot_id:str
    realization_identity:str
    recovery_epoch:int
    current_baseline_version:int
    activation_result_ref:str=""
    safety_hold:bool=False
    revocation_reason:str=""
