from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum
from types import MappingProxyType


class ProductionState(StrEnum):
    PR_00_INITIATED="PR-00_INITIATED"
    PR_01_BASELINE_LOCKED="PR-01_BASELINE_LOCKED"
    PR_02_DESIGN_CANDIDATE="PR-02_DESIGN_CANDIDATE"
    PR_03_DESIGN_REVIEW_PENDING="PR-03_DESIGN_REVIEW_PENDING"
    PR_04_DESIGN_REPAIR_AUTHORIZED="PR-04_DESIGN_REPAIR_AUTHORIZED"
    PR_04E_DESIGN_EVIDENCE_REMEDIATION_REQUIRED="PR-04E_DESIGN_EVIDENCE_REMEDIATION_REQUIRED"
    PR_05_DESIGN_APPROVED="PR-05_DESIGN_APPROVED"
    PR_06_DESIGN_FROZEN="PR-06_DESIGN_FROZEN"
    PR_07_IMPLEMENTATION_HANDOFF_READY="PR-07_IMPLEMENTATION_HANDOFF_READY"
    PR_08_IMPLEMENTATION_IN_PROGRESS="PR-08_IMPLEMENTATION_IN_PROGRESS"
    PR_09_IMPLEMENTATION_CANDIDATE="PR-09_IMPLEMENTATION_CANDIDATE"
    PR_10_IMPLEMENTATION_REVIEW_PENDING="PR-10_IMPLEMENTATION_REVIEW_PENDING"
    PR_11_IMPLEMENTATION_REPAIR_AUTHORIZED="PR-11_IMPLEMENTATION_REPAIR_AUTHORIZED"
    PR_12_DESIGN_REOPEN_REQUIRED="PR-12_DESIGN_REOPEN_REQUIRED"
    PR_13_SHARED_REVIEW_REQUIRED="PR-13_SHARED_REVIEW_REQUIRED"
    PR_14_REVIEW_EVIDENCE_REMEDIATION_REQUIRED="PR-14_REVIEW_EVIDENCE_REMEDIATION_REQUIRED"
    PR_15_IMPLEMENTATION_APPROVED="PR-15_IMPLEMENTATION_APPROVED"
    PR_15R_BASELINE_RECONCILIATION_REQUIRED="PR-15R_BASELINE_RECONCILIATION_REQUIRED"
    PR_16_IMPLEMENTATION_FROZEN="PR-16_IMPLEMENTATION_FROZEN"
    PR_17_RUN_COMPLETE="PR-17_RUN_COMPLETE"


class ProductionEvent(StrEnum):
    BASELINE_LOCKED="BASELINE_LOCKED"
    DESIGN_CANDIDATE_PRODUCED="DESIGN_CANDIDATE_PRODUCED"
    DESIGN_REVIEW_SUBMITTED="DESIGN_REVIEW_SUBMITTED"
    DESIGN_REPAIR_AUTHORIZED="DESIGN_REPAIR_AUTHORIZED"
    DESIGN_CANDIDATE_REVISED="DESIGN_CANDIDATE_REVISED"
    DESIGN_EVIDENCE_REMEDIATION_AUTHORIZED="DESIGN_EVIDENCE_REMEDIATION_AUTHORIZED"
    DESIGN_EVIDENCE_REMEDIATED="DESIGN_EVIDENCE_REMEDIATED"
    SHARED_REVIEW_REQUIRED="SHARED_REVIEW_REQUIRED"
    SHARED_BASELINE_FROZEN="SHARED_BASELINE_FROZEN"
    DESIGN_REVIEW_PASS="DESIGN_REVIEW_PASS"
    DESIGN_FROZEN="DESIGN_FROZEN"
    IMPLEMENTATION_HANDOFF_COMPLETED="IMPLEMENTATION_HANDOFF_COMPLETED"
    CODING_BEGINS="CODING_BEGINS"
    IMPLEMENTATION_CANDIDATE_READY="IMPLEMENTATION_CANDIDATE_READY"
    IMPLEMENTATION_REVIEW_SUBMITTED="IMPLEMENTATION_REVIEW_SUBMITTED"
    IMPLEMENTATION_REPAIR_AUTHORIZED="IMPLEMENTATION_REPAIR_AUTHORIZED"
    IMPLEMENTATION_CANDIDATE_REVISED="IMPLEMENTATION_CANDIDATE_REVISED"
    DESIGN_REOPEN_REQUIRED="DESIGN_REOPEN_REQUIRED"
    DESIGN_REOPEN_COMPLETED="DESIGN_REOPEN_COMPLETED"
    IMPLEMENTATION_EVIDENCE_REMEDIATION_AUTHORIZED="IMPLEMENTATION_EVIDENCE_REMEDIATION_AUTHORIZED"
    IMPLEMENTATION_EVIDENCE_REMEDIATED="IMPLEMENTATION_EVIDENCE_REMEDIATED"
    IMPLEMENTATION_REVIEW_PASS="IMPLEMENTATION_REVIEW_PASS"
    IMPLEMENTATION_FROZEN_ACCEPTED="IMPLEMENTATION_FROZEN_ACCEPTED"
    STALE_BASELINE_DETECTED="STALE_BASELINE_DETECTED"
    STALE_RECONCILED_NO_DESIGN_CHANGE="STALE_RECONCILED_NO_DESIGN_CHANGE"
    STALE_RECONCILIATION_INVALIDATES_DESIGN="STALE_RECONCILIATION_INVALIDATES_DESIGN"
    CANONICAL_CLOSURE_COMPLETE="CANONICAL_CLOSURE_COMPLETE"


# Exact transition relation copied from canonical Frozen Factory v1.11 B08 implementation.
_PAIRS = (
(PR_00:=ProductionState.PR_00_INITIATED, ProductionEvent.BASELINE_LOCKED, ProductionState.PR_01_BASELINE_LOCKED),
(ProductionState.PR_01_BASELINE_LOCKED,ProductionEvent.DESIGN_CANDIDATE_PRODUCED,ProductionState.PR_02_DESIGN_CANDIDATE),
(ProductionState.PR_02_DESIGN_CANDIDATE,ProductionEvent.DESIGN_REVIEW_SUBMITTED,ProductionState.PR_03_DESIGN_REVIEW_PENDING),
(ProductionState.PR_03_DESIGN_REVIEW_PENDING,ProductionEvent.DESIGN_REPAIR_AUTHORIZED,ProductionState.PR_04_DESIGN_REPAIR_AUTHORIZED),
(ProductionState.PR_04_DESIGN_REPAIR_AUTHORIZED,ProductionEvent.DESIGN_CANDIDATE_REVISED,ProductionState.PR_02_DESIGN_CANDIDATE),
(ProductionState.PR_03_DESIGN_REVIEW_PENDING,ProductionEvent.DESIGN_EVIDENCE_REMEDIATION_AUTHORIZED,ProductionState.PR_04E_DESIGN_EVIDENCE_REMEDIATION_REQUIRED),
(ProductionState.PR_04E_DESIGN_EVIDENCE_REMEDIATION_REQUIRED,ProductionEvent.DESIGN_EVIDENCE_REMEDIATED,ProductionState.PR_03_DESIGN_REVIEW_PENDING),
(ProductionState.PR_03_DESIGN_REVIEW_PENDING,ProductionEvent.SHARED_REVIEW_REQUIRED,ProductionState.PR_13_SHARED_REVIEW_REQUIRED),
(ProductionState.PR_13_SHARED_REVIEW_REQUIRED,ProductionEvent.SHARED_BASELINE_FROZEN,ProductionState.PR_01_BASELINE_LOCKED),
(ProductionState.PR_03_DESIGN_REVIEW_PENDING,ProductionEvent.DESIGN_REVIEW_PASS,ProductionState.PR_05_DESIGN_APPROVED),
(ProductionState.PR_05_DESIGN_APPROVED,ProductionEvent.DESIGN_FROZEN,ProductionState.PR_06_DESIGN_FROZEN),
(ProductionState.PR_06_DESIGN_FROZEN,ProductionEvent.IMPLEMENTATION_HANDOFF_COMPLETED,ProductionState.PR_07_IMPLEMENTATION_HANDOFF_READY),
(ProductionState.PR_07_IMPLEMENTATION_HANDOFF_READY,ProductionEvent.CODING_BEGINS,ProductionState.PR_08_IMPLEMENTATION_IN_PROGRESS),
(ProductionState.PR_08_IMPLEMENTATION_IN_PROGRESS,ProductionEvent.IMPLEMENTATION_CANDIDATE_READY,ProductionState.PR_09_IMPLEMENTATION_CANDIDATE),
(ProductionState.PR_09_IMPLEMENTATION_CANDIDATE,ProductionEvent.IMPLEMENTATION_REVIEW_SUBMITTED,ProductionState.PR_10_IMPLEMENTATION_REVIEW_PENDING),
(ProductionState.PR_10_IMPLEMENTATION_REVIEW_PENDING,ProductionEvent.IMPLEMENTATION_REPAIR_AUTHORIZED,ProductionState.PR_11_IMPLEMENTATION_REPAIR_AUTHORIZED),
(ProductionState.PR_11_IMPLEMENTATION_REPAIR_AUTHORIZED,ProductionEvent.IMPLEMENTATION_CANDIDATE_REVISED,ProductionState.PR_09_IMPLEMENTATION_CANDIDATE),
(ProductionState.PR_10_IMPLEMENTATION_REVIEW_PENDING,ProductionEvent.DESIGN_REOPEN_REQUIRED,ProductionState.PR_12_DESIGN_REOPEN_REQUIRED),
(ProductionState.PR_12_DESIGN_REOPEN_REQUIRED,ProductionEvent.DESIGN_REOPEN_COMPLETED,ProductionState.PR_07_IMPLEMENTATION_HANDOFF_READY),
(ProductionState.PR_10_IMPLEMENTATION_REVIEW_PENDING,ProductionEvent.SHARED_REVIEW_REQUIRED,ProductionState.PR_13_SHARED_REVIEW_REQUIRED),
(ProductionState.PR_10_IMPLEMENTATION_REVIEW_PENDING,ProductionEvent.IMPLEMENTATION_EVIDENCE_REMEDIATION_AUTHORIZED,ProductionState.PR_14_REVIEW_EVIDENCE_REMEDIATION_REQUIRED),
(ProductionState.PR_14_REVIEW_EVIDENCE_REMEDIATION_REQUIRED,ProductionEvent.IMPLEMENTATION_EVIDENCE_REMEDIATED,ProductionState.PR_10_IMPLEMENTATION_REVIEW_PENDING),
(ProductionState.PR_10_IMPLEMENTATION_REVIEW_PENDING,ProductionEvent.IMPLEMENTATION_REVIEW_PASS,ProductionState.PR_15_IMPLEMENTATION_APPROVED),
(ProductionState.PR_15_IMPLEMENTATION_APPROVED,ProductionEvent.IMPLEMENTATION_FROZEN_ACCEPTED,ProductionState.PR_16_IMPLEMENTATION_FROZEN),
(ProductionState.PR_15_IMPLEMENTATION_APPROVED,ProductionEvent.STALE_BASELINE_DETECTED,ProductionState.PR_15R_BASELINE_RECONCILIATION_REQUIRED),
(ProductionState.PR_15R_BASELINE_RECONCILIATION_REQUIRED,ProductionEvent.STALE_RECONCILED_NO_DESIGN_CHANGE,ProductionState.PR_09_IMPLEMENTATION_CANDIDATE),
(ProductionState.PR_15R_BASELINE_RECONCILIATION_REQUIRED,ProductionEvent.STALE_RECONCILIATION_INVALIDATES_DESIGN,ProductionState.PR_12_DESIGN_REOPEN_REQUIRED),
(ProductionState.PR_16_IMPLEMENTATION_FROZEN,ProductionEvent.CANONICAL_CLOSURE_COMPLETE,ProductionState.PR_17_RUN_COMPLETE),
)
ALLOWED_TRANSITIONS=MappingProxyType({(a,b):c for a,b,c in _PAIRS})


@dataclass(frozen=True, slots=True)
class ProductionRunRecord:
    production_run_id: str
    current_state: ProductionState
    consistency_version: int
    recovery_epoch: int
    exact_candidate_id: str
    upstream_handoff_ref: str
    last_transition_ref: str = ""


def transition(run: ProductionRunRecord, event: ProductionEvent, *, transition_ref: str) -> ProductionRunRecord:
    try:
        nxt=ALLOWED_TRANSITIONS[(run.current_state,event)]
    except KeyError as exc:
        raise PermissionError(f"INVALID_TRANSITION:{run.current_state.value}+{event.value}") from exc
    return ProductionRunRecord(
        production_run_id=run.production_run_id,current_state=nxt,
        consistency_version=run.consistency_version+1,recovery_epoch=run.recovery_epoch,
        exact_candidate_id=run.exact_candidate_id,upstream_handoff_ref=run.upstream_handoff_ref,
        last_transition_ref=transition_ref,
    )
